package br.com.ronick.album.visao;

import br.com.ronick.album.modelo.bd.AlbumBD;
import br.com.ronick.album.modelo.dao.FigurinhaDAO;
import br.com.ronick.album.modelo.dao.IrmaoDAO;
import br.com.ronick.album.modelo.entidade.Figurinha;
import br.com.ronick.album.modelo.entidade.Irmao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AlbumGUI extends javax.swing.JFrame {

    private int pagina;

    /**
     * Creates new form AlbumGUI
     */
    public AlbumGUI() {
        initComponents();
        AlbumBD.popular();
        pagina = 1;
        atualiza();
    }

    private void atualiza() {
        String[] cposIrmao = {"ID", "Nome", "Contato"};
        List<Irmao> irmaos = IrmaoDAO.selecionarTodos();
        String[][] dadosIrmaos;
        dadosIrmaos = new String[irmaos.size()][3];
        int posicao = 0;
        for (Irmao ir : irmaos) {
            String[] umIrmao = new String[3];
            umIrmao[0] = String.valueOf(ir.getId());
            umIrmao[1] = ir.getNome();
            umIrmao[2] = ir.getContato();
            dadosIrmaos[posicao++] = umIrmao;
        }
        DefaultTableModel modelo = new DefaultTableModel(
                dadosIrmaos, cposIrmao);
        jtIrmaos.setModel(modelo);
        String[] cposFigurinha = {"Número", "Página", "Descr.", "Qtde"};
        List<Figurinha> figurinhas = FigurinhaDAO.selecionarPorPagina(pagina);
        String[][] dadosFigurinhas;
        dadosFigurinhas = new String[figurinhas.size()][4];
        posicao = 0;
        for (Figurinha fig : figurinhas) {
            String[] umaFigurinha = new String[4];
            umaFigurinha[0] = String.valueOf(fig.getNumero());
            umaFigurinha[1] = String.valueOf(fig.getPagina());
            umaFigurinha[2] = fig.getDescricao();
            umaFigurinha[3] = String.valueOf(fig.getQuantidade());
            dadosFigurinhas[posicao++] = umaFigurinha;
        }
        DefaultTableModel modeloFig = new DefaultTableModel(
                dadosFigurinhas, cposFigurinha);
        jTable1.setModel(modeloFig);
    }

    public int retornaQtde(String id) {
        List<Figurinha> coletaID = FigurinhaDAO.selecionarPorId(Integer.parseInt(id));
        int qtde = 0;
        for (Figurinha colId : coletaID) {
            qtde = colId.getQuantidade();
        }
        return qtde;
    }

    public void adicionarFigurinha(String numero, byte qtde) {
        String descricao = JOptionPane.showInputDialog(rootPane, "Digite a descrição:", "Adicionar Figurinha", 1);
        if (descricao != null) {
            Figurinha figurinha = new Figurinha(Integer.parseInt(numero), (byte) pagina, descricao, qtde);
            FigurinhaDAO.inserir(figurinha);
        }
    }

    public void alteraQtde(String id, int operacao) {
        List<Figurinha> figTroca = FigurinhaDAO.selecionarPorId(Integer.parseInt(id));
        int numero, qtde;
        byte pagina;
        String descricao;
        Figurinha figNova = null;
        for (Figurinha fig : figTroca) {
            numero = fig.getNumero();
            pagina = fig.getPagina();
            descricao = fig.getDescricao();
            qtde = fig.getQuantidade() + operacao;
            figNova = new Figurinha(numero, pagina, descricao, (byte) qtde);
        }
        FigurinhaDAO.alterar(figNova);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAlbum = new javax.swing.JPanel();
        jtpAbas = new javax.swing.JTabbedPane();
        jpIrmaos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtIrmaos = new javax.swing.JTable();
        jbNovoIrmao = new javax.swing.JButton();
        jbRemoverIrmao = new javax.swing.JButton();
        jbModificarIrmao = new javax.swing.JButton();
        jpFigurinhas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbDescricao = new javax.swing.JButton();
        jbAdicionar = new javax.swing.JButton();
        jbRetirar = new javax.swing.JButton();
        jbTrocar = new javax.swing.JButton();
        jbAnterior = new javax.swing.JButton();
        jbProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Album da Copa 2022");
        setResizable(false);

        jtIrmaos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtIrmaos);

        jbNovoIrmao.setText("Adicionar");
        jbNovoIrmao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoIrmaoActionPerformed(evt);
            }
        });

        jbRemoverIrmao.setText("Remover");
        jbRemoverIrmao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverIrmaoActionPerformed(evt);
            }
        });

        jbModificarIrmao.setText("Modificar");
        jbModificarIrmao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarIrmaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIrmaosLayout = new javax.swing.GroupLayout(jpIrmaos);
        jpIrmaos.setLayout(jpIrmaosLayout);
        jpIrmaosLayout.setHorizontalGroup(
            jpIrmaosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jpIrmaosLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jbNovoIrmao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRemoverIrmao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbModificarIrmao)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jpIrmaosLayout.setVerticalGroup(
            jpIrmaosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIrmaosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jpIrmaosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovoIrmao)
                    .addComponent(jbRemoverIrmao)
                    .addComponent(jbModificarIrmao))
                .addContainerGap())
        );

        jtpAbas.addTab("Irmãos", jpIrmaos);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbDescricao.setText("Descrição");
        jbDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDescricaoActionPerformed(evt);
            }
        });

        jbAdicionar.setText("Adicionar");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        jbRetirar.setText("Retirar");
        jbRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRetirarActionPerformed(evt);
            }
        });

        jbTrocar.setText("Trocar");
        jbTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTrocarActionPerformed(evt);
            }
        });

        jbAnterior.setText("Anterior");
        jbAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnteriorActionPerformed(evt);
            }
        });

        jbProximo.setText("Próxima");
        jbProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFigurinhasLayout = new javax.swing.GroupLayout(jpFigurinhas);
        jpFigurinhas.setLayout(jpFigurinhasLayout);
        jpFigurinhasLayout.setHorizontalGroup(
            jpFigurinhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jpFigurinhasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jbDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbRetirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTrocar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jpFigurinhasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbAdicionar, jbAnterior, jbDescricao, jbProximo, jbRetirar, jbTrocar});

        jpFigurinhasLayout.setVerticalGroup(
            jpFigurinhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFigurinhasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jpFigurinhasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDescricao)
                    .addComponent(jbAdicionar)
                    .addComponent(jbRetirar)
                    .addComponent(jbTrocar)
                    .addComponent(jbAnterior)
                    .addComponent(jbProximo))
                .addContainerGap())
        );

        jtpAbas.addTab("Figurinhas", jpFigurinhas);

        javax.swing.GroupLayout jpAlbumLayout = new javax.swing.GroupLayout(jpAlbum);
        jpAlbum.setLayout(jpAlbumLayout);
        jpAlbumLayout.setHorizontalGroup(
            jpAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpAbas)
                .addContainerGap())
        );
        jpAlbumLayout.setVerticalGroup(
            jpAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpAbas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRetirarActionPerformed
        String id = JOptionPane.showInputDialog(rootPane, "Digite o numero do ID a ser removido:", "Retirar figurinha", 1);
        if (id != null) {
            int testeFigurinha = retornaQtde(id);
            if (testeFigurinha == 1) {
                Figurinha figurinha = new Figurinha(Integer.parseInt(id), (byte) pagina, "Indefinida", (byte) 0);
                FigurinhaDAO.alterar(figurinha);
            } else if (testeFigurinha > 1) {
                alteraQtde(id, -1);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não possui esta figurinha");
            }
        }
        atualiza();
    }//GEN-LAST:event_jbRetirarActionPerformed

    private void jbTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTrocarActionPerformed
        String id = JOptionPane.showInputDialog(rootPane, "Digite o numero da Figurinha para trocar:",
                "Trocar figurinha", 1);
        String irmao = JOptionPane.showInputDialog(rootPane, "Digite o nome do irmão que irá trocar:",
                "Trocar figurinha", 1);
        if (id != null && irmao != null) {
            if (retornaQtde(id) > 0) {
                List<Irmao> irmaoTroca = IrmaoDAO.selecionarPorNome(irmao);
                if (irmaoTroca.size() == 1) {
                    String idNovo = JOptionPane.showInputDialog(rootPane, "Digite o numero da Figurinha que Recebeu:",
                            "Trocar figurinha", 1);
                    int testeQtdeId = retornaQtde(id);
                    int testeQtdeIdNovo = retornaQtde(idNovo);
                    if (testeQtdeId == 1 && testeQtdeIdNovo == 0) {
                        Figurinha figurinha = new Figurinha(Integer.parseInt(id), (byte) pagina, "Indefinida", (byte) 0);
                        FigurinhaDAO.alterar(figurinha);
                        adicionarFigurinha(idNovo, (byte) 1);
                    } else if (testeQtdeId == 1 && testeQtdeIdNovo > 0) {
                        Figurinha figurinha = new Figurinha(Integer.parseInt(id), (byte) pagina, "Indefinida", (byte) 0);
                        FigurinhaDAO.alterar(figurinha);
                        alteraQtde(idNovo, 1);
                    } else if (testeQtdeId > 1 && testeQtdeIdNovo == 0) {
                        alteraQtde(id, -1);
                        adicionarFigurinha(idNovo, (byte) 1);
                    } else {
                        alteraQtde(id, -1);
                        alteraQtde(idNovo, 1);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, String.format("Você não possui um irmão chamado %s", irmao));
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não possui essa figurinha");
            }
        }
        atualiza();
    }//GEN-LAST:event_jbTrocarActionPerformed

    private void jbRemoverIrmaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverIrmaoActionPerformed
        String id = JOptionPane.showInputDialog(rootPane, "Digite o numero do ID a ser removido:", "Remover Irmão", 1);
        if (id != null) {
            IrmaoDAO.remover(Integer.parseInt(id));
        }
        atualiza();
    }//GEN-LAST:event_jbRemoverIrmaoActionPerformed

    private void jbNovoIrmaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoIrmaoActionPerformed
        String nome = JOptionPane.showInputDialog(rootPane, "Digite o nome:", "Novo Irmão", 1);
        String contato = JOptionPane.showInputDialog(rootPane, "Digite o contato:", "Novo Irmão", 1);
        if (nome != null && contato != null) {
            Irmao irmao = new Irmao(nome, contato);
            IrmaoDAO.inserir(irmao);
        }
        atualiza();
    }//GEN-LAST:event_jbNovoIrmaoActionPerformed

    private void jbModificarIrmaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarIrmaoActionPerformed
        String id = JOptionPane.showInputDialog(rootPane, "Digite o numero do ID a ser alterado:", "Alterar Irmão", 1);
        String nome = JOptionPane.showInputDialog(rootPane, "Digite o novo nome:", "Alterar Irmão", 1);
        String contato = JOptionPane.showInputDialog(rootPane, "Digite o novo contato:", "Alterar Irmão", 1);
        if (id != null && nome != null && contato != null) {
            Irmao irmao = new Irmao(Byte.parseByte(id), nome, contato);
            IrmaoDAO.alterar(irmao);
        }
        atualiza();
    }//GEN-LAST:event_jbModificarIrmaoActionPerformed

    private void jbAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnteriorActionPerformed
        if (pagina > 1) {
            pagina--;
            atualiza();
        }
    }//GEN-LAST:event_jbAnteriorActionPerformed

    private void jbProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximoActionPerformed
        if (pagina < 30) {
            pagina++;
            atualiza();
        }
    }//GEN-LAST:event_jbProximoActionPerformed

    private void jbDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDescricaoActionPerformed
        String id = JOptionPane.showInputDialog(rootPane, "Digite o numero do ID a ser alterado:", "Alterar Descrição", 1);
        String descricao = JOptionPane.showInputDialog(rootPane, "Digite a nova descrição:", "Alterar Descrição", 1);
        Figurinha figurinha;
        if (id != null && descricao != null) {
            if (retornaQtde(id) > 0) {
                figurinha = new Figurinha(Integer.parseInt(id), (byte) pagina, descricao, (byte) retornaQtde(id));
                FigurinhaDAO.alterar(figurinha);
                atualiza();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não possui esta Figurinha");
            }
        }
    }//GEN-LAST:event_jbDescricaoActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        String numero = JOptionPane.showInputDialog(rootPane, "Digite o numero da Figurinha:", "Adicionar Figurinha", 1);
        if (numero != null) {
            List<Figurinha> figurinha = FigurinhaDAO.selecionarPorId(Integer.parseInt(numero));
            for (Figurinha fig : figurinha) {
                if (fig.getQuantidade() == 0) {
                    adicionarFigurinha(numero, (byte) 1);
                } else {
                    alteraQtde(numero, 1);
                }
            }
        }
        atualiza();
    }//GEN-LAST:event_jbAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlbumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlbumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlbumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlbumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlbumGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbAnterior;
    private javax.swing.JButton jbDescricao;
    private javax.swing.JButton jbModificarIrmao;
    private javax.swing.JButton jbNovoIrmao;
    private javax.swing.JButton jbProximo;
    private javax.swing.JButton jbRemoverIrmao;
    private javax.swing.JButton jbRetirar;
    private javax.swing.JButton jbTrocar;
    private javax.swing.JPanel jpAlbum;
    private javax.swing.JPanel jpFigurinhas;
    private javax.swing.JPanel jpIrmaos;
    private javax.swing.JTable jtIrmaos;
    private javax.swing.JTabbedPane jtpAbas;
    // End of variables declaration//GEN-END:variables
}
